[project]
name = "agent001"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.9.0",
    "ipywidgets>=8.1.7",
    "llm>=0.26",
    "llm-gemini>=0.23",
    "playwright>=1.53.0",
    "sclog>=0.1.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
